import type { Theme } from '../types'

// Black Ash — a near-black, low-glow dark theme. Chrome sits at true black-ash,
// the editor surface lifts a hair above it, with a cool azure accent so active
// states stay legible without lighting up the whole UI.
export const blackAsh: Theme = {
  meta: { id: 'black-ash', name: 'Black Ash', appearance: 'dark' },
  chrome: {
    background: '#0c0c0e',
    surface: '#08080a',
    surfaceSecondary: '#0c0c0e',
    surfaceTertiary: '#1c1c20',
    foreground: '#cdd0d6',
    muted: '#6b6e76',
    accent: '#7dd3fc',
    accentForeground: '#08080a',
    border: '#1a1a1e',
    separator: '#1a1a1e',
    success: '#86efac',
    warning: '#fcd34d',
    danger: '#f87171',
    link: '#7dd3fc',
    focus: '#7dd3fc',
    scrollbar: '#3a3a42',
    fieldBackground: '#101013',
    fieldBorder: 'rgba(160, 165, 175, 0.16)',
    overlay: '#101013',
    backdrop: 'rgba(0, 0, 0, 0.7)',
  },
  terminal: {
    cursor: '#cdd0d6',
    selection: 'rgba(125, 211, 252, 0.25)',
    ansi: {
      black: '#1a1a1e',
      red: '#f87171',
      green: '#86efac',
      yellow: '#fcd34d',
      blue: '#7dd3fc',
      magenta: '#d8b4fe',
      cyan: '#67e8f9',
      white: '#cdd0d6',
      brightBlack: '#4b4b54',
      brightRed: '#fca5a5',
      brightGreen: '#bbf7d0',
      brightYellow: '#fde68a',
      brightBlue: '#93c5fd',
      brightMagenta: '#e9d5ff',
      brightCyan: '#a5f3fc',
      brightWhite: '#f4f4f6',
    },
  },
  syntax: {
    comment: '#5a5d65',
    keyword: '#d8b4fe',
    string: '#86efac',
    number: '#fca5a5',
    function: '#7dd3fc',
    variable: '#cdd0d6',
    type: '#67e8f9',
    constant: '#fca5a5',
    operator: '#93c5fd',
    punctuation: '#9ca3af',
    tag: '#f87171',
    attribute: '#fcd34d',
    heading: '#7dd3fc',
    link: '#7dd3fc',
  },
}
