import type { Theme } from '../types'

// Port of bchiang7/halcyon-vscode — the original wTerm palette.
// Deep navy chrome, slightly lighter editor surface, yellow accent.
export const halcyon: Theme = {
  meta: { id: 'halcyon', name: 'Halcyon', appearance: 'dark' },
  chrome: {
    background: '#1d2433',
    surface: '#171c28',
    surfaceSecondary: '#1d2433',
    surfaceTertiary: '#2f3b54',
    foreground: '#a2aabc',
    muted: '#5c6773',
    accent: '#ffcc66',
    accentForeground: '#171c28',
    border: '#2f3b54',
    separator: '#2f3b54',
    success: '#bae67e',
    warning: '#ffcc66',
    danger: '#ef6b73',
    link: '#5ccfe6',
    focus: '#ffcc66',
    scrollbar: '#96a6cc',
    fieldBackground: '#1d2433',
    fieldBorder: 'rgba(150, 166, 204, 0.2)',
    overlay: '#1d2433',
    backdrop: 'rgba(0, 0, 0, 0.6)',
  },
  terminal: {
    cursor: '#ffcc66',
    selection: 'rgba(255, 204, 102, 0.3)',
    ansi: {
      black: '#2f3b54',
      red: '#ef6b73',
      green: '#bae67e',
      yellow: '#ffcc66',
      blue: '#5ccfe6',
      magenta: '#c3a6ff',
      cyan: '#5ccfe6',
      white: '#a2aabc',
      brightBlack: '#444a5e',
      brightRed: '#ef6b73',
      brightGreen: '#bae67e',
      brightYellow: '#ffcc66',
      brightBlue: '#5ccfe6',
      brightMagenta: '#c3a6ff',
      brightCyan: '#5ccfe6',
      brightWhite: '#d7dce2',
    },
  },
  syntax: {
    comment: '#5c6773',
    keyword: '#c3a6ff',
    string: '#bae67e',
    number: '#f78c6c',
    function: '#5ccfe6',
    variable: '#a2aabc',
    type: '#ffd580',
    constant: '#f78c6c',
    operator: '#ffcc66',
    punctuation: '#8695b7',
    tag: '#5ccfe6',
    attribute: '#ffd580',
    heading: '#ffcc66',
    link: '#5ccfe6',
  },
}
