//! The built web client, embedded at compile time.
//!
//! `web_client.html` is generated by the `remote-web` package (a single
//! self-contained file produced by `npm run build` there, which copies it here).
//! It is committed so the crate always compiles without a Node build in the loop;
//! rebuild `remote-web` whenever the web client changes.

pub const WEB_CLIENT: &str = include_str!("web_client.html");
